alias gs="git_util_status"
alias gb="git_utils_branch"
alias ga="git_utils_sub add status"
alias gc="git_utils_sub commit status"
alias gd="git_utils_sub diff status"
alias gres="git_utils_sub restore status"
alias gress="git_utils_sub restore status --staged"
alias gresw="git_utils_sub restore status --worktree"
alias gressw="git_utils_sub restore status -s@ -SW"

alias gca="git add --all . && git commit"
alias gco="echo 'Use git restore and git switch.'"
alias gsw="git_utils_sub switch branch"
alias gm="git_utils_sub merge branch"
alias gma="git merge --abort"
alias grb="git_utils_sub rebase branch"
alias grbi="git_utils_sub rebase branch -i"
alias grbc="git rebase --continue"
alias grba="git rebase --abort"

gl_format="--pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'"
alias gl="git log --graph ${gl_format} --abbrev-commit"
