alias gs="git_util_status"
alias gb="git_util_branch"
alias ga="git_util_sub add status"
alias gc="git_util_sub commit status"
alias guns="git_util_sub restore status --staged"
alias gres="git_util_sub restore status --worktree"

alias gca="git add --all . && git commit"
alias gco="echo 'Use git restore and git switch.'"
alias gsw="git_util_sub switch branch"
alias gm="git_util_sub merge branch"
alias gma="git merge --abort"
alias grb="git_util_sub rebase branch"
alias grbi="git_util_sub rebase branch -i"
alias grbc="git rebase --continue"
alias grba="git rebase --abort"
